

apiVersion: v1
kind: Service
metadata:
  name: myapp-upgrade
  namespace: infra
  labels:
    app: myapp-upgrade
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: myapp-upgrade


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-upgrade
  namespace: infra
  labels:
    app: myapp-upgrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-upgrade
  template:
    metadata:
      name: myapp-upgrade
      labels:
        app: myapp-upgrade
    spec:
      containers:
        - name: myapp-upgrade
          image: tencentmusic/myapp:myapp-upgrade
          imagePullPolicy: Always  # IfNotPresent
          command: ["python","server.py"]    # 如果修改了entrypoint要使用命令执行
          ports:
            - name: http
              containerPort: 80
              protocol: TCP